### PR TITLE
Fix some issues

### LINKED ISSUE #17: crash in TemplateMatchCandidates::findCandidates
I observe crash on this assert:

        CV_Assert(
            templ.type() == CV_MAKETYPE(CV_8U, _integrals.size()) &&
            templ.size() == _templateSize && 
            (templMask.empty() || templMask.size() == _templateSize));

the problem is that templ.size() == _templateSize is FALSE. This is because _templateSize=[19,19] and templ is just [9,9]. Templ is [9,9] since centeredPatch<PATCHFLAGS> returns half size of patch (because targetPatchLocation=(0,0) so it had to cut patch in half).

### PR DESCRIPTION
**Pull request by scribblemaniac**
This PR is mainly to make the brush strokes more responsive and fix #17. I also fixed a couple more minor things and refactoring as I came across them, see the commits for details.

### CODE REVIEW

**Comment by cheind** [comment]
Did you run the tests successfully?

**Comment by scribblemaniac** [comment]
Yes all tests passed.

**Comment by cheind** [comment]
I'll run them after merge. Thanks and happy holidays!

**Comment by scribblemaniac** [comment]
Cheers :+1:

**Pull request merged**
